from __main__ import *

BATCH_SIZE = 128
FILTERS = 32
EPOCHS = 200
VERBOSE = 2
MODEL_PATH = file_path_dict[LAYER_NAME]
PICKLE_PATH = LAYER_NAME + '_hist.pkl'

DATA_SIZE = 60000

PRIOR_MU = 0
PRIOR_SIGMA = 10
N_PREDICTIONS = 100
